# Generated by Django 3.1.6 on 2021-03-18 17:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210218_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 17, 49, 50, 575889, tzinfo=utc)),
        ),
    ]
