# Generated by Django 3.1.6 on 2021-03-18 17:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210318_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 17, 54, 42, 775382, tzinfo=utc)),
        ),
    ]
