# Generated by Django 2.2.18 on 2021-03-18 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210318_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 18, 13, 33, 732336, tzinfo=utc)),
        ),
    ]
