# Generated by Django 2.2.18 on 2021-03-21 17:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210321_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 17, 35, 27, 667984, tzinfo=utc)),
        ),
    ]
